version: '3.3'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile-proxy
      args:
        - USER_ID=${WWWUSER:-1000}
        - GROUP_ID=${WWWGROUP:-1000}
        - USER=${USER:-whoami}
        - HTTP_PROXY=http://172.16.2.254:3128
    container_name: expennies-app
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9003:9003"
    volumes:
      - ../:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - http_proxy=http://172.16.2.254:3128
      - https_proxy=http://172.16.2.254:3128
      - HTTP_PROXY=http://172.16.2.254:3128
      - HTTPS_PROXY=http://172.16.2.254:3128
      - no_proxy=localhost,127.0.0.1,host.docker.internal
      - DNS_SERVER=8.8.8.8
  nginx:
    image: nginx:1.19-alpine
    container_name: expennies-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./storage:/var/www/storage
  db:
    container_name: expennies-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  mailhog:
    container_name: expennies-mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"
